### ISSUE TITLE
Wrong usage in README

### ISSUE THREAD

**Issue by kota65535** [endorama/asdf-parse-tool-versions#165]
Action output is JSON, so the usage in README should be like this:

```
      # OR using action output
      - name: install Go
        uses: actions/setup-go@v1
        with: 
          go-version: ${{ fromJSON(steps.versions.outputs.tools).golang }}
```
